project_id = "cxtinhcxatyvxsqncujw"

[functions.end-chat]
verify_jwt = false

[functions.delete-media]
verify_jwt = false

[functions.cleanup-empty-rooms]
verify_jwt = false

[functions.cleanup-expired-messages]
verify_jwt = false

[functions.verify-room-password]
verify_jwt = false

[functions.tenor-search]
verify_jwt = false
